# Generated by Django 6.0.5 on 2026-05-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("bilibili", "B站"),
                            ("xiaohongshu", "小红书"),
                            ("douyin", "抖音"),
                        ],
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                (
                    "creator_id",
                    models.CharField(max_length=100, verbose_name="创作者ID"),
                ),
                (
                    "creator_name",
                    models.CharField(max_length=200, verbose_name="创作者名称"),
                ),
                (
                    "creator_avatar",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="创作者头像",
                    ),
                ),
                (
                    "creator_desc",
                    models.TextField(blank=True, default="", verbose_name="创作者简介"),
                ),
                (
                    "rsshub_route",
                    models.CharField(max_length=500, verbose_name="RSSHub 路由"),
                ),
                (
                    "group",
                    models.CharField(
                        default="default", max_length=100, verbose_name="分组"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "platform", "creator_id")},
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("bilibili", "B站"),
                            ("xiaohongshu", "小红书"),
                            ("douyin", "抖音"),
                        ],
                        max_length=20,
                        verbose_name="平台",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, default="", max_length=1000, verbose_name="链接"
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True, default="", max_length=1000, verbose_name="封面图"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="作者"
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(db_index=True, verbose_name="发布时间"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="抓取时间"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="feeds.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-pub_date"],
                "unique_together": {("subscription", "link")},
            },
        ),
        migrations.CreateModel(
            name="UserEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                ("is_starred", models.BooleanField(default=False, verbose_name="收藏")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_entries",
                        to="feeds.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "entry")},
            },
        ),
    ]
